### ISSUE TITLE
Another Druidcraft crash

### ISSUE THREAD

**Issue by Devintrainer** [Noobulus/Tetra-Pak#8] opened 2021-09-11 20:01 UTC
[The report](https://pastebin.com/AdJ3YQ2E)

This is a bit of an odd situation. The mod crashes due to Druidcraft's moonstrike effect. Wasn't this fixed a while ago? Or is this a new crash related to it?

**Comment by Noobulus** [comment] 2021-09-11 20:07
This crash is caused by some internal changes in the latest version of Tetra. This issue is fixed in dev (08bd76c), so it should be fixed in the next release. Thanks for reporting!

**Comment by Noobulus** [comment] 2021-09-11 23:17
Fixed in [latest release](https://www.curseforge.com/minecraft/mc-mods/tetra-pak/files/3456988) (i hope). Thanks for reporting!

**Closed** 2021-09-18 08:54 UTC
